name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: out
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.leesdonnerstag }}
          password: ${{ secrets.defenitlynotatoken }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:  nebelmahr/ttd-frontend:${{github.run_number}} 